# Generated by Django 3.1.1 on 2020-10-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_auto_20201009_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linked_in_id',
            new_name='linkedin_id',
        ),
    ]
